//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblpersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpersonel()
        {
            this.tblsatislar = new HashSet<tblsatislar>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage ="Personel Adý Alanýný Boþ Geçemezsiniz!")]
        [StringLength(30,ErrorMessage ="Personel Adý 30 Karakterden Fazla Olamaz!")]
        public string ad { get; set; }

        [Required(ErrorMessage = "Personel Soyadý Alanýný Boþ Geçemezsiniz!")]
        [StringLength(30, ErrorMessage = "Personel Soyadý 30 Karakterden Fazla Olamaz!")]
        public string soyad { get; set; }

        [Required(ErrorMessage = "Departman Alanýný Boþ Geçemezsiniz!")]
        [StringLength(30, ErrorMessage = "Departman 30 Karakterden Fazla Olamaz!")]
        public string departman { get; set; }
        public Nullable<bool> durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatislar> tblsatislar { get; set; }
    }
}
